### ISSUE TITLE
Byzantium supports success/fail tx

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/ico-wizard#292]
https://ethereum.stackexchange.com/questions/28077/how-do-i-detect-a-failed-transaction-after-the-byzantium-fork-as-the-revert-opco/28078?stw=2#28078

every tx receipt is now has status:
`status: "0x1",` - success
` status: "0x0",` - fail

if it was called by `revert`

**Comment by fernandomg** [comment]
So far this is doable, but MetaMask is having issues sending the error to the Dapp (https://github.com/MetaMask/metamask-extension/issues/2060) so the Dapp never gets a response from the contract method call.

In the other hand, I've been trying with Mist but I'm experiencing this issue: https://github.com/ethereum/mist/issues/2131.

So I'd wait for those problems to be fixed in order to continue with this issue, otherwise is too hard to develop and test.

**Comment by rstormsf** [comment]
what issues? why do u use testrpc? testrpc is not real node, so don't expect testrpc to support it

**Comment by fvictorio** [comment]
testrpc does support Byzantium features: https://github.com/ethereumjs/testrpc/issues/402

What do you use for development if not testrpc?
