### ISSUE TITLE
(Bug) Transaction runs out of gas during deployment step

### ISSUE THREAD

**Issue by fvictorio** [oraclesorg/ico-wizard#316]
The deployment step fails because one of the transactions runs out of gas (during the first call to `setLastCrowdsaleRecursive`, I think).

One possible solution is to remove the `gasLimit`s in the code and rely on the inferred gas cost, that should work fine because these transactions should be predictable.

I can send a PR with this change if you think it's a good solution.

**Comment by vbaranov** [comment]
`gasLimit` was set in this [commit](https://github.com/oraclesorg/ico-wizard/commit/e641e2476a45bde24711f2bbaa8a01c534e0f6cb#diff-9ad076eec5a57203bda5be84b5b322a8) for contract methods, due to the issue in mainnet: when wizard hangs on the one of the method of contract. If it won't cause problems in the mainnet, I vote for this solution. If not, as a workaround, let's increase gasLimit for this tx.

**Comment by fvictorio** [comment]
I can test it in Kovan to see that it doesn't causes problems. Is that enough or do you test this kind of things in the mainnet too, using real ether?

**Comment by igorbarinov** [comment]
@fvictorio we can deploy it on `stage` without review and I'll test it on mainnet.
Also, please post here your wallet and I'll send you some mainnet eth for testing

**Comment by fvictorio** [comment]
I've thought about this a little more and I don't think my idea will work. The networks have different gas limits by default, and web3 doesn't have an option to set a new default gas limit: you have to do it in each transaction. This, and the fact that a transaction sometimes exceeds the default of 90000, makes it necessary to use gas limits per transaction anyway.

So, I'll send a PR with updated gas limits for now.

@igorbarinov I created an address at `0x4a9a263d09f3722f5a97619ca77816abdb63d8fd`
